INVOICESMANA/INVOICESMANA/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using INVOICESMANA.DATA;
using INVOICESMANA.DATA.Common;
using INVOICESMANA.Models;
using System.IO;
using INVOICESMANA.Helper;
using System.Net;
using System.Web.Script.Serialization;
using Newtonsoft.Json;
using System.Globalization;
using System.Transactions;

namespace INVOICESMANA.Controllers
{
    [Authorize]
    public class CompanyController : Controller
    {
        // GET: Company
        [LogFilterAttribute(ModuleId = "9cbfdfc3-dab3-46dc-88d0-eac5d7e31fdf")]
        public ActionResult Index()
        {

            return View();
        }

        public ActionResult GetCompanies(DataTableParams _params)
        {
            DataTableRespond result = new DataTableRespond();
            result.data = new List<Company>();
            try
            {
                using (var uow = new UnitOfWork())
                {
                    List<CompanyModel> res = new List<CompanyModel>();
                    var total = uow.CompaniesRepository.GetAll();
                    result.recordsTotal = total.Count();
                    result.recordsFiltered = total.Count();
                    switch (_params.iSortCol_0)
                    {
                        case 0:
                            {
                                if (_params.sSortDir_0 == "asc")
                                {
                                    total = total.OrderBy(x => x.CompanyCode).ToList();
                                }
                                else
                                {
                                    total = total.OrderByDescending(x => x.CompanyCode).ToList();
                                }
                                break;
                            }
                        case 1:
                            {
                                if (_params.sSortDir_0 == "asc")
                                {
                                    total = total.OrderBy(x => x.Name).ToList();
                                }
                                else
                                {
                                    total = total.OrderByDescending(x => x.Name).ToList();
                                }
                                break;
                            }
                        case 2:
                            {
                                if (_params.sSortDir_0 == "asc")
                                {
                                    total = total.OrderBy(x => x.Address).ToList();
                                }
                                else
                                {
                                    total = total.OrderByDescending(x => x.Address).ToList();
                                }
                                break;
                            }
                        case 3:
                            {
                                if (_params.sSortDir_0 == "asc")
                                {
                                    total = total.OrderBy(x => x.CreatedDate).ToList();
                                }
                                else
                                {
                                    total = total.OrderByDescending(x => x.CreatedDate).ToList();
                                }
                                break;
                            }
                        case 4:
                            {
                                if (_params.sSortDir_0 == "asc")
                                {
                                    total = total.OrderBy(x => x.PMS).ToList();
                                }
                                else
                                {
                                    total = total.OrderByDescending(x => x.PMS).ToList();
                                }
                                break;
                            }
                        case 5:
                            {
                                if (_params.sSortDir_0 == "asc")
                                {
                                    total = total.OrderBy(x => x.Status).ToList();
                                }
                                else
                                {
                                    total = total.OrderByDescending(x => x.Status).ToList();
                                }
                                break;
                            }
                    }
                    if (!string.IsNullOrEmpty(_params.sSearch))
                    {
                        total = total.Where(x => x.Name.ToLower().Contains(_params.sSearch.ToLower())).ToList();
                        result.recordsFiltered = total.Count();
                    }

                    var temp = total.Skip(_params.iDisplayStart).Take(_params.iDisplayLength);
                    if (temp.Any())
                    {
                        foreach (var r in temp)
                        {
                            res.Add(new CompanyModel
                            {
                                CompanyId = r.CompanyId,
                                CompanyCode = r.CompanyCode,
                                Name = r.Name,
                                Address = r.Address,
                                CreatedDate = r.CreatedDate,
                                InvoiceType = r.InvoiceType,
                                PMS = r.PMS,
                                Status = r.Status,
                                IsUses = Session["UserId"] == null
                            });
                        }
                    }
                    result.data = res;
                }
            }
            catch (Exception ex)
            {

            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Update(Guid companyid)
        {
            ViewBag.Title = "Chi tiết";
            var uow = new UnitOfWork();
            Company company = uow.CompaniesRepository.GetById(companyid);
            if (company.Logo != null)
            {
                if (System.IO.File.Exists(Server.MapPath(Url.Content(ConfigurationManager.AppSettings["logoCompanyPath"] + company.Logo))))
                {
                    company.Logo = Url.Content(ConfigurationManager.AppSettings["logoCompanyPath"] + company.Logo);
                }
                else
                {
                    company.Logo = Url.Content("~/Content/images/no-logo.jpg");
                }
            }

            return View("Detail", company);
        }

        [HttpPost]
        public ActionResult Update()
        {
            Result result = new Result();
            try
            {
                var comReq = new CompanyModel();
                comReq = JsonConvert.DeserializeObject<CompanyModel>(Request.Params["comReq"]);

                if (comReq.invoiceTypes == null && comReq.invoiceTypes.Count < 1)
                {
                    result.Code = -1;
                    result.Message = "Thông tin mẫu hóa đơn và ký hiệu";
                }

                if (!Directory.Exists(Server.MapPath(ConfigurationManager.AppSettings["logoCompanyPath"])))
                {
                    Directory.CreateDirectory(Server.MapPath(ConfigurationManager.AppSettings["logoCompanyPath"]));
                }
                bool changeLogo = false;
                var context = HttpContext;

                if (Request.Files.Count > 0)
                {
                    HttpPostedFileBase file = Request.Files[0];
                    string fileName = file.FileName;
                    string fileExtension = file.ContentType;

                    fileExtension = Path.GetExtension(fileName);
                    string str_image = "LOGO-" + Guid.NewGuid() + fileExtension;
                    string pathToSave = Server.MapPath(ConfigurationManager.AppSettings["logoCompanyPath"] + str_image);
                    file.SaveAs(pathToSave);
                    comReq.Logo = str_image;
                    changeLogo = true;
                }
                using (TransactionScope scope = new TransactionScope(TransactionScopeOption.Required))
                {
                    using (var uow = new UnitOfWork())
                    {
                        Company com = uow.CompaniesRepository.GetById(comReq.CompanyId);
                        var types = uow.InvoiceTypeRepository.GetWhere(x => x.CompanyId == com.CompanyId).ToList();
                        uow.InvoiceTypeRepository.DeleteRange(types);
                        uow.SaveChanges();
                        if (com != null)
                        {
                            if (changeLogo == true)
                            {
                                com.Logo = comReq.Logo;
                            }
                            com.Name = comReq.Name;
                            com.Address = comReq.Address;
                            com.Email = comReq.Email;
                            com.Phone = comReq.Phone;
                            com.TaxIdentification = comReq.TaxIdentification;
                            com.Account = comReq.Account;
                            com.Password = comReq.Password;
                            com.Status = comReq.Status;
                            com.InvoiceType = comReq.InvoiceType;
                            com.PMS = comReq.PMS;
                            com.CompanyCode = comReq.CompanyCode;
                            com.Token = comReq.Token;
                            com.ExpiryDate = comReq.ExpiryDate;
                            com.CreatedDate = comReq.CreatedDate;
                            com.CreatedBy = Helper.Identity.UserId;

INVOICESMANA/INVOICESMANA/Views/Shared/_Layout.cshtml
@using INVOICESMANA.Helper
@using System.Globalization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <input type="hidden" value="@Identity.IsSuperAdmin.ToString().ToLower()" id="IsSuperAdmin" />
    <input type="hidden" id="sysFormat" value="@CultureInfo.CurrentCulture.DateTimeFormat.ShortDatePattern" />
    <input type="hidden" id="sysUIFormat" value="@CultureInfo.CurrentUICulture.DateTimeFormat.ShortDatePattern" />
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="~/">ezInvoices</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    @if (new Permision(Guid.Parse("26ad318c-7db8-477b-9839-22aaa416884e")).IsViewAllowed)
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Quản lý nhân viên
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="@(Url.Action("Users", "Account"))"><i class="fa fa-users" aria-hidden="true"></i>Quản lý tài khoản</a></li>
                                <li><a href="@(Url.Action("Index", "Role"))"><i class="fa fa-address-card-o" aria-hidden="true"></i>Phân quyền</a></li>
                            </ul>
                        </li>
                    }
                    @if (new Permision(Guid.Parse("9cbfdfc3-dab3-46dc-88d0-eac5d7e31fdf")).IsViewAllowed)
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Quản lý đơn vị
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="@(Url.Action("Index", "Company"))"><i class="fa fa-building-o" aria-hidden="true"></i>Quản lý đơn vị</a></li>
                            </ul>
                        </li>
                    }
                    @if (new Permision(Guid.Parse("96289b7d-d686-4e2e-9986-7d20e930d394")).IsViewAllowed)
                    {
                        if (Session["Companyid"] != null)
                        {
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    Quản lý hóa đơn
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    @if (Session["Type"] == "1")
                                    {
                                        <li><a href="@(Url.Action("Index", "Invoice"))"><i class="fa fa-file-o" aria-hidden="true"></i>Danh sách hóa đơn</a></li>

                                    }
                                    else
                                    {
                                        <li><a href="@(Url.Action("Index", "ViettelInvoice"))"><i class="fa fa-file-o" aria-hidden="true"></i>Danh sách hóa đơn</a></li>
                                    }
                                </ul>
                            </li>
                        }

                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (Session["CompanyName"] != null)
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle">Đơn vị: @Session["CompanyName"].ToString()</a>
                        </li>
                    }
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Chào&nbsp;@Identity.UserName &nbsp;<span class="glyphicon glyphicon-user"></span></a>
                        <ul class="dropdown-menu">
                            @{
                                if (!Identity.IsSuperAdmin)
                                {
                                    <li><a href="@Url.Action("MyAccount", "Account", new { UserId = Identity.UserId })">Tài khoản của tôi</a></li>
                                }
                            }
                            <li><a href="@(Url.Action("LogOff", "Account"))"><i class="fa fa-sign-out" aria-hidden="true"></i>Đăng xuất</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    <!--Loader-->
    <div class="loader" style="display: none;">
        <div class="loader-icon">

        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")

    <script type="text/javascript">
        $(document).ready(function () {
            window.UrlConfig = {};
            window.UrlConfig.AppUrl = '@Url.Content("/")';
        })
    </script>

    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/appscript")
    @RenderSection("scripts", required: false)
</body>
</html>

INVOICESMANA/INVOICESMANA/Views/Shared/_LayoutAccount.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>