INVOICESMANA/INVOICESMANA/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using INVOICESMANA.Helper;
using INVOICESMANA.Models;
using INVOICESMANA.DATA;
using INVOICESMANA.DATA.Common;
using System.Net;
using System.IO;
using System.Configuration;
using INVOICESMANA.Controllers;

namespace INVOICESMANA.Controllers
{
    [Authorize]
    public class InvoiceController : Controller
    {
        // GET: Invoice
        [LogFilterAttribute(ModuleId = "96289b7d-d686-4e2e-9986-7d20e930d394")]
        public ActionResult Index()
        {
            if (Session["UserId"] != null)
            {
                var userId = new Guid(Session["UserId"].ToString());
                using (var uow = new UnitOfWork())
                {
                    var user = uow.UserRepository.GetById(userId);
                    if (user != null)
                    {
                        var company = uow.CompaniesRepository.GetById(user.CompanyId);
                        if (company != null)
                        {
                            ViewBag.CompanyId = company.CompanyId;
                        }
                    }
                }
            }

            if (Session["CompanyId"] == null)
            {
                return RedirectToAction("Index", "Company");
            }

            return View();
        }

        [LogFilterAttribute(ModuleId = "96289b7d-d686-4e2e-9986-7d20e930d394")]
        public ActionResult AddNew()
        {
            if (Session["UserId"] != null)
            {
                var userId = new Guid(Session["UserId"].ToString());
                using (var uow = new UnitOfWork())
                {
                    var user = uow.UserRepository.GetById(userId);
                    if (user != null)
                    {
                        var company = uow.CompaniesRepository.GetById(user.CompanyId);
                        if (company != null)
                        {
                            ViewBag.CompanyId = company.CompanyId;
                        }
                    }
                }
            }
            if (Session["CompanyId"] == null)
            {
                return RedirectToAction("Index", "Company");
            }

            ViewBag.EditMode = "false";
            ViewBag.Title = "Thêm hóa đơn";
            return View("Detail");
        }

        [LogFilterAttribute(ModuleId = "96289b7d-d686-4e2e-9986-7d20e930d394")]
        public ActionResult Detail(Guid? id)
        {
            if (Session["UserId"] != null)
            {
                var userId = new Guid(Session["UserId"].ToString());
                using (var uow = new UnitOfWork())
                {
                    var user = uow.UserRepository.GetById(userId);
                    if (user != null)
                    {
                        ViewBag.CompanyId = user.CompanyId;
                    }
                }
            }

            if (Session["CompanyId"] == null)
            {
                return RedirectToAction("Index", "Company");
            }

            if (id.HasValue == false)
            {
                return RedirectToAction("Index");
            }

            ViewBag.InvoiceId = id;
            ViewBag.EditMode = "true";
            ViewBag.Title = "Chi tiết hóa đơn";
            return View("Detail");
        }

        [LogFilterAttribute(ModuleId = "96289b7d-d686-4e2e-9986-7d20e930d394")]
        public ActionResult Invoice(Guid? companyId)
        {
            if (companyId.HasValue)
            {
                using (var uow = new UnitOfWork())
                {
                    var company = uow.CompaniesRepository.GetById(companyId.Value);
                    if (company != null)
                    {
                        ViewBag.CompanyId = company.CompanyId;
                        Session["CompanyName"] = company.Name;
                        Session["CompanyId"] = company.CompanyId;
                        Session["Type"] = (int)InvoiceTypes.mInvoice;
                    }
                }
            }
            return RedirectToAction("Index");
        }

        public ActionResult getCombobox()
        {
            Result result = new Result();
            DroplistDependency res = new DroplistDependency();
            try
            {
                using (var uow = new UnitOfWork())
                {
                    res.VAT = new List<SelectItem>();
                    var VAT = uow.VatRepository.GetAll();
                    if (VAT.Any())
                    {
                        foreach (var v in VAT)
                        {
                            res.VAT.Add(new SelectItem() { Value = v.VatValue.ToString(), Text = v.Name });
                        }
                    }

                    res.PaymentType = new List<SelectItem>();
                    var paymentType = uow.PaymentTypeRepository.GetAll();
                    if (paymentType.Any())
                    {
                        foreach (var p in paymentType)
                        {
                            res.PaymentType.Add(new SelectItem() { Value = p.PaymentId.ToString(), Text = p.Name });
                        }
                    }
                }
                result.Data = res;
            }
            catch (Exception ex)
            {
                result.Code = -1;
                result.Message = ex.Message;
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult getListInvoice(DataTableParams _params)
        {
            DataTableRespond result = new DataTableRespond();
            result.data = new List<Invoice>();
            try
            {
                using (var uow = new UnitOfWork())
                {
                    var invoices = uow.InvoicesRepository.GetAll().AsQueryable();
                    result.recordsTotal = invoices.Count();
                    result.recordsFiltered = invoices.Count();

                    if (invoices.Any())
                    {
                        switch (_params.iSortCol_0)
                        {
                            case 0:
                                {
                                    if (_params.sSortDir_0 == "asc")
                                    {
                                        invoices = invoices.OrderBy(x => x.InvoiceNumber);
                                    }
                                    else
                                    {
                                        invoices = invoices.OrderByDescending(x => x.InvoiceNumber);
                                    }
                                    break;
                                }
                            case 1:
                                {
                                    if (_params.sSortDir_0 == "asc")
                                    {
                                        invoices = invoices.OrderBy(x => x.OrderNumber);
                                    }
                                    else
                                    {
                                        invoices = invoices.OrderByDescending(x => x.OrderNumber);
                                    }
                                    break;
                                }
                            case 2:
                                {
                                    if (_params.sSortDir_0 == "asc")
                                    {
                                        invoices = invoices.OrderBy(x => x.ContractDate);
                                    }
                                    else
                                    {
                                        invoices = invoices.OrderByDescending(x => x.ContractDate);
                                    }
                                    break;
                                }
                            case 3:
                                {
                                    if (_params.sSortDir_0 == "asc")
                                    {
                                        invoices = invoices.OrderBy(x => x.Customer.FullName);
                                    }
                                    else
                                    {
                                        invoices = invoices.OrderByDescending(x => x.Customer.FullName);
                                    }
                                    break;
                                }
                            case 4:
                                {
                                    if (_params.sSortDir_0 == "asc")
                                    {
                                        invoices = invoices.OrderBy(x => x.Company.Name);
                                    }
                                    else
                                    {
                                        invoices = invoices.OrderByDescending(x => x.Company.Name);
                                    }
                                    break;
                                }
                            case 5:
                                {
                                    if (_params.sSortDir_0 == "asc")
                                    {
                                        invoices = invoices.OrderBy(x => x.Customer.Address);
                                    }
                                    else
                                    {
                                        invoices = invoices.OrderByDescending(x => x.Customer.Address);
                                    }
                                    break;
                                }
                            case 6:
                                {
                                    if (_params.sSortDir_0 == "asc")
                                    {

INVOICESMANA/INVOICESMANA/Views/Invoice/Detail.cshtml
@using INVOICESMANA.Helper
@{
    ViewBag.ModuleId = "96289b7d-d686-4e2e-9986-7d20e930d394";
}

<h2 class="page-title">
    @ViewBag.Title
    @Html.ActionLink("Quay lại", "Index", "Invoice", null, new { @class = "btn btn-default pull-right" }) &nbsp;
    <button class="btn btn-primary pull-right" id="ExportInvoice" style="display:none; margin-right: 10px;">Phát hành</button> &nbsp;
    <button class="btn btn-primary pull-right" id="UpdateIdentificationInvoice" style="display:none; margin-right: 10px;">Điều chỉnh định danh</button> &nbsp;
    <button class="btn btn-primary pull-right" id="UpdateLowInvoice" style="display:none; margin-right: 10px;">Điều chỉnh giảm</button> &nbsp;
    <button class="btn btn-primary pull-right" id="UpdateHighInvoice" style="display:none; margin-right: 10px;">Điều chỉnh tăng</button> &nbsp;
    <button class="btn btn-primary pull-right" id="ChangeInvoice" style="display:none; margin-right: 10px;">Thay thế</button> &nbsp;
    <button class="btn btn-danger pull-right" id="DeleteInvoice" style="display:none; margin-right: 10px;">Hủy</button>
</h2>
<input type="hidden" id="ModuleId" value="@ViewBag.ModuleId" />
<input type="hidden" id="EditMode" value="@ViewBag.EditMode" />
<input type="hidden" id="InvoiceId" value="@ViewBag.InvoiceId" />
<input type="hidden" id="CompanyId" value="@Session["CompanyId"]" />
<div class="row invoice-detail-container">
    <div class="form-horizontal" id="InvoiceContainer">
        <div class="col-sm-12">
            <div class="row">
                <div class="col-md-4">
                    <h4 class="group-info-title">Thông tin hóa đơn</h4>
                    <div class="form-group">
                        <label class="control-label col-sm-4" for="InvoiceType">Mẫu số</label>
                        <div class="col-sm-8">
                            <select class="form-control" id="InvoiceType" required></select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-sm-4" for="InvoiceSeries">Kí hiệu</label>
                        <div class="col-sm-8">
                            <select class="form-control" id="InvoiceSeries" required></select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-4" for="ContractDate">Ngày HĐ</label>
                        <div class="col-sm-8">
                            <div class="input-group" id="ContractDate">
                                <input class="form-control" value="" required />
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar">
                                    </span>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="row mgtop-137">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="control-label col-sm-4" for="ContractNumber">Số HĐ</label>
                                <div class="col-sm-8">
                                    <input class="form-control" id="ContractNumber" value="" required />
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="control-label col-sm-4" for="OrderNumber">Số đơn hàng</label>
                                <div class="col-sm-8">
                                    <input class="form-control" id="OrderNumber" value="" required />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <h4 class="group-info-title">Thông tin thanh toán</h4>
                    <div class="form-group">
                        <label class="control-label col-sm-4" for="PaymentId">Hình thức thanh toán</label>
                        <div class="col-sm-8">
                            <select class="form-control" id="PaymentId" name="PaymentId" required></select>
                        </div>
                    </div>

                    <div id="payment" >
                        <div class="form-group">
                            <label class="control-label col-sm-4" for="Account">Tài khoản</label>
                            <div class="col-sm-8">
                                <input class="form-control" id="Account" value="" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-4" for="Bank">Ngân hàng</label>
                            <div class="col-sm-8">
                                <input class="form-control" id="Bank" value="" />
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>

        <div class="col-sm-12">
            <div class="row">
                <div class="col-sm-4">
                    <h4 class="group-info-title">Thông tin người mua</h4>
                    <div class="form-group">
                        <label class="control-label col-sm-4" for="CustomerCode">Mã khách hàng</label>
                        <div class="col-sm-8">
                            <input class="form-control" id="CustomerCode" value="" required />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-sm-4" for="CustomerFullName">Tên người mua</label>
                        <div class="col-sm-8">
                            <input class="form-control" id="CustomerFullName" value="" required />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-sm-4" for="CustomerTaxIdentification">Mã số thuế</label>
                        <div class="col-sm-8">
                            <input class="form-control" id="CustomerTaxIdentification" value="" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-sm-4" for="CustomerAddress">Địa chỉ</label>
                        <div class="col-sm-8">
                            <input class="form-control" id="CustomerAddress" value="" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-sm-4" for="CustomerAccountNumber">Tài khoản</label>
                        <div class="col-sm-8">
                            <input class="form-control" id="CustomerAccountNumber" value="" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-sm-4" for="CustomerBank">Ngân hàng</label>
                        <div class="col-sm-8">
                            <input class="form-control" id="CustomerBank" value="" />
                        </div>
                    </div>
                </div>
                <div class="col-sm-4">
                    <h4>&nbsp;</h4>
                    <div class="form-group">
                        <label class="control-label col-sm-4" for="CustomerCompanyName">Tên đơn vị</label>
                        <div class="col-sm-8">
                            <input class="form-control" id="CustomerCompanyName" value="" />
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-12">
            <div class="row">
                <h4 class="group-info-title">Chi tiết hóa đơn</h4>
                <table class="table table-bordered table-striped" id="InvoiceDetail">
                    <thead>
                        <tr>
                            <th>Mã hàng</th>
                            <th>Tên hàng</th>
                            <th>Đơn vị</th>
                            <th>Số lượng</th>
                            <th>Đơn giá</th>
                            <th>Tiền</th>
                            <th>%CK</th>
                            <th>Tiền CK</th>
                            <th>Thuế</th>
                            <th>Tiền thuế</th>
                            <th>Thành tiền</th>
                            <th style="display: none">Id</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <td colspan="6" id="TotalAmount" class="align-right text-bold">&nbsp;</td>
                            <td colspan="2" id="DiscountAmount" class="align-right text-bold">&nbsp;</td>
                            <td colspan="2" id="VatAmount" class="align-right text-bold">&nbsp;</td>
                            <td id="Total" class="align-right text-bold">&nbsp;</td>
                        </tr>
                        <tr>
                            <td colspan="11">
                                <button class="btn btn-primary" id="AddDetail"><span class="glyphicon glyphicon-plus-sign"></span>&nbsp; Thêm sản phẩm</button>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        var InvoicesMana = new InvoicesManagement();
        InvoicesMana.initDetail();
    </script>
}

INVOICESMANA/INVOICESMANA/Views/Invoice/Index.cshtml
@using INVOICESMANA.Helper;
@{
    ViewBag.Title = "Danh sách hóa đơn";
    ViewBag.ModuleId = "96289b7d-d686-4e2e-9986-7d20e930d394";
}

<h2 class="page-title">
    @ViewBag.Title
    @if (new Permision(Guid.Parse(ViewBag.ModuleId)).IsAddAllowed)
    {
        <a class="btn btn-primary pull-right" href="@Url.Action("AddNew", "Invoice")">Thêm mới</a>
    }
</h2>
<input type="hidden" id="ModuleId" value="@ViewBag.ModuleId" />
<input type="hidden" id="CompanyId" value="@Session["CompanyId"]" />
<input type="hidden" id="UserId" value="@Identity.UserName" />

<div class="row">
    <div class="col-md-12">
        <table class="table table-bordered table-striped" id="ListInvoiceTable">
            <thead>
                <tr>
                    <th>Số HĐ</th>
                    <th>Số đơn hàng</th>
                    <th>Ngày HD</th>
                    <th>Tên người mua</th>
                    <th>Tên đơn vị</th>
                    <th>Địa chỉ</th>
                    <th>Email</th>
                    <th>Tổng tiền</th>
                    <th>PTTT</th>
                    <th>Thao tác</th>
                </tr>
            </thead>
        </table>
    </div>
</div>

@section scripts{
    <script>
        var InvoicesMana = new InvoicesManagement();
        InvoicesMana.initList();
    </script>
}